"""Deterministic seed derivation for Praxis validator checks.

This module is internal to ``praxis.checks`` -- the leading underscore
signals that it is not part of any public API.
"""

from __future__ import annotations

import hashlib
from typing import Final

from praxis.protocol.hashing import canonical_bytes
from praxis.protocol.manifest import EnvManifest

__all__ = ["derive_validator_seeds"]

_SEED_MASK: Final[int] = (1 << 63) - 1  # int64-safe range
_SEED_BYTES: Final[int] = 8
_SEEDS_PER_BLOCK: Final[int] = 8  # 64-byte digest / 8-byte seed


def derive_validator_seeds(
    manifest: EnvManifest,
    n: int,
    salt: bytes,
) -> tuple[int, ...]:
    """Deterministically derive N pseudo-random seeds from env-defining
    parts of an EnvManifest, with a per-check salt.

    Hashed inputs (in this order, NUL-separated):
        env_id, env_version, entry_point, canonical_bytes(kwargs), salt

    Deliberately EXCLUDED: declared_reward_bounds, anchor_trajectories,
    creator_metadata. This prevents a creator from tweaking those fields
    (the things they declare claims about) to shift the seeds the
    validator samples. Creators commit env behavior via the included
    fields and cannot reshape the validator's sample seeds without
    changing the env itself.

    Phase 1 collusion-resistance limitation (intentional):
        A determined adversary can brute-force the 4-tuple
        (env_id, env_version, entry_point, kwargs) to find one whose
        derived seeds happen to coincide with their preferred lying-set.
        Search cost grows quickly with n. Phase 2 hardening will layer
        a chain-beacon-derived salt on top so seeds become unpredictable
        per-validation-epoch even given the manifest.

    Multi-block strategy: BLAKE2b is capped at 64 bytes (8 seeds) per
    digest. For n > 8, additional blocks are generated by appending a
    4-byte little-endian block index to the input before hashing. Each
    block contributes 8 seeds; results are truncated to exactly n seeds.

    Args:
        manifest: the env manifest under test.
        n: number of seeds to produce. Must be >= 1.
        salt: per-check identifier (e.g. b"reward_bounds",
              b"reset_correctness"). Must be non-empty.

    Returns:
        Tuple of n (in expectation distinct) non-negative ints in
        [0, 2**63 - 1].

    Raises:
        ValueError: if n < 1 or salt is empty.
    """
    if n < 1:
        raise ValueError(f"n must be >= 1, got {n}")
    if len(salt) == 0:
        raise ValueError("salt must be non-empty")

    seeds: list[int] = []
    blocks_needed = (n + _SEEDS_PER_BLOCK - 1) // _SEEDS_PER_BLOCK
    for block_idx in range(blocks_needed):
        h = hashlib.blake2b(digest_size=64)
        h.update(manifest.env_id.encode("utf-8"))
        h.update(b"\x00")
        h.update(manifest.env_version.encode("utf-8"))
        h.update(b"\x00")
        h.update(manifest.entry_point.encode("utf-8"))
        h.update(b"\x00")
        h.update(canonical_bytes(manifest.kwargs))
        h.update(b"\x00")
        h.update(salt)
        h.update(b"\x00")
        h.update(block_idx.to_bytes(4, "little"))
        digest = h.digest()
        for i in range(_SEEDS_PER_BLOCK):
            raw = int.from_bytes(digest[i * _SEED_BYTES : (i + 1) * _SEED_BYTES], "little")
            seeds.append(raw & _SEED_MASK)

    return tuple(seeds[:n])
